
const allProducrts = [
    { color: "red", brand: "apple", name: "Apple iPhone 5", descript: "lorem sdfsdf ewrwe ssdf", price: "100" },
    { color: "black", brand: "apple", name: "Apple iPhone 3g", descript: "lorem sdfsdf ewrwe ssdf", price: "80" },
    { color: "green", brand: "apple", name: "Apple iPhone 6", descript: "lorem sdfsdf ewrwe ssdf", price: "150" },
    { color: "blue", brand: "apple", name: "Apple iPhone 13", descript: "lorem sdfsdf ewrwe ssdf", price: "1000" },
    { color: "red", brand: "apple", name: "Apple iPhone 14", descript: "lorem sdfsdf ewrwe ssdf", price: "1200" },
    { color: "red", brand: "apple", name: "Apple iPad", descript: "lorem sdfsdf ewrwe ssdf", price: "600" },
        { color: "red", brand: "apple", name: "Apple iPhone 5", descript: "lorem sdfsdf ewrwe ssdf", price: "100" },
    { color: "black", brand: "apple", name: "Apple iPhone 6", descript: "lorem sdfsdf ewrwe ssdf", price: "150" },
    { color: "black", brand: "apple", name: "Apple iPhone 13", descript: "lorem sdfsdf ewrwe ssdf", price: "700" },
    { color: "black", brand: "apple", name: "Apple iPhone 14", descript: "lorem sdfsdf ewrwe ssdf", price: "1200" },
    { color: "green", brand: "apple", name: "Apple iPad", descript: "lorem sdfsdf ewrwe ssdf", price: "600" },
    { color: "blue", brand: "samsung", name: "Samsung Star S5230", descript: "lorem sdfsdf ewrwe ssdf", price: "25" },
    { color: "red", brand: "lenovo", name: "Lenovo Idea Pad", descript: "lorem sdfsdf ewrwe ssdf", price: "900" },
    { color: "blue", brand: "acer", name: "Acer", descript: "lorem sdfsdf ewrwe ssdf", price: "1010" },
    { color: "red", brand: "lenovo", name: "s43", descript: "lorem sdfsdf ewrwe ssdf", price: "143" },
    { color: "black", brand: "lenovo", name: "start32", descript: "lorem sdfsdf ewrwe ssdf", price: "954" },    { brand: "apple", name: "Apple iPhone 5", descript: "lorem sdfsdf ewrwe ssdf", price: "100" },
    { color: "black", brand: "apple", name: "Apple iPhone 6", descript: "lorem sdfsdf ewrwe ssdf", price: "150" },
    { color: "black", brand: "apple", name: "Apple iPhone 13", descript: "lorem sdfsdf ewrwe ssdf", price: "800" },
    { color: "black", brand: "samsung", name: "multiphone", descript: "lorem sdfsdf ewrwe ssdf", price: "1200" },
    { color: "black", brand: "samsung", name: "duos", descript: "lorem sdfsdf ewrwe ssdf", price: "600" },
    { color: "red", brand: "samsung", name: "Samsung Star S5230", descript: "lorem sdfsdf ewrwe ssdf", price: "25" },
    { color: "red", brand: "lenovo", name: "Lenovo Idea Pad", descript: "lorem sdfsdf ewrwe ssdf", price: "900" },
    {color: "blue", brand: "acer", name: "Acer", descript: "lorem sdfsdf ewrwe ssdf", price: "1010" },
    {color: "blue", brand: "acer", name: "acer a54", descript: "lorem sdfsdf ewrwe ssdf", price: "10032" },
    {color: "blue", brand: "apple", name: "Apple iPhone 99", descript: "lorem sdfsdf ewrwe ssdf", price: "100" },    { brand: "apple", name: "Apple iPhone 5", descript: "lorem sdfsdf ewrwe ssdf", price: "100" },
    {color: "blue", brand: "apple", name: "Apple iPhone 6", descript: "lorem sdfsdf ewrwe ssdf", price: "150" },
    {color: "blue", brand: "acer", name: "acer s13", descript: "lorem sdfsdf ewrwe ssdf", price: "1000" },
    {color: "blue", brand: "apple", name: "Apple iPhone 14", descript: "lorem sdfsdf ewrwe ssdf", price: "1200" },
    {color: "blue", brand: "apple", name: "Apple iPad", descript: "lorem sdfsdf ewrwe ssdf", price: "600" },
    {color: "blue", brand: "samsung", name: "Samsung Star S5230", descript: "lorem sdfsdf ewrwe ssdf", price: "25" },
    {color: "blue", brand: "lenovo", name: "Lenovo Idea Pad", descript: "lorem sdfsdf ewrwe ssdf", price: "900" },
    {color: "blue", brand: "acer", name: "Acer", descript: "lorem sdfsdf ewrwe ssdf", price: "101000" },
    {color: "blue", brand: "acer", name: "acer 54", descript: "lorem sdfsdf ewrwe ssdf", price: "100000" },
    {color: "blue", brand: "apple", name: "Apple iPhone 99", descript: "lorem sdfsdf ewrwe ssdf", price: "100000000" },
    {color: "blue", brand: "samsung", name: "Samsung Star S5230", descript: "lorem sdfsdf ewrwe ssdf", price: "25" },
    {color: "blue", brand: "lenovo", name: "Lenovo Idea Pad", descript: "lorem sdfsdf ewrwe ssdf", price: "900" },
    {color: "green", brand: "acer", name: "Acer", descript: "lorem sdfsdf ewrwe ssdf", price: "101" },
    {color: "green", brand: "acer", name: "acer 54", descript: "lorem sdfsdf ewrwe ssdf", price: "100000" },
    {color: "green", brand: "apple", name: "Apple iPhone 99", descript: "lorem sdfsdf ewrwe ssdf", price: "100000000" },
              
]

export default allProducrts